### ISSUE TITLE
Integrated air filter blueprint

### ISSUE THREAD

**Issue by BorisBarczyk** [Cattlesquat/subnautica#3]
Hello Cattlesquat,
I've been enjoying your mod for about 15 hour now and i can't find the blueprint for the integrated air filter. I searched for over an hour on the internet and still couldn't find a single clue as how to get the blueprint. I would really appreciate it if you could tell me how to get it.

**Comment by Cattlesquat** [comment]
Although I've mostly forgotten how these things worked, I took a look in the code and it *looks* like it would unlock when you unlock the Cyclops.

**Comment by BorisBarczyk** [comment]
Yep, it worked. Thanks for the info.
