### ISSUE TITLE
Extract Randomized Starting Location to its own Mod

### ISSUE THREAD

**Issue by jet082** [Cattlesquat/subnautica#6]
I would quite enjoy being able to play the game via a random starting location. Ideally at least one in each biome (and ideally one that swaps our escape pod with one of the other ones in the game - it’d make for an interesting ‘what if we were swapped with someone else’ scenario).

The other extreme changes in this mod, while fun, are a bit over my head for right now. Would it be possible to make a separate mod for just randomized starting locations?

**Comment by Cattlesquat** [comment]
I don't do separate mods but anyone is welcome to fork this repo and do it if they want. Note that you can turn most of the features of this mod off with the preferences already offered.

**Comment by jet082** [comment]
Oh that’s fair enough. Thanks for that info.
